app = 'bot-checklist-obras'
primary_region = 'gru'

[build]
  builder = 'paketobuildpacks/builder:base'

[processes]
  app = 'python bot.py'

[mounts]
  source = "checklist_data"
  destination = "/data"

[[vm]]
  memory = '256mb'
  cpus = 1